### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by formlessdao** [user202729/plover-resources#1]
Hi, link is broken, can you upload the file please ? https://www.ncra.org/files/MCMS/5E781983-A6C9-4EA3-BCDD-B33ED6998381.pdf

**Comment by user202729** [comment]
It's already.

> A file [...] was **originally** available [here](https://www.ncra.org/files/MCMS/5E781983-A6C9-4EA3-BCDD-B33ED6998381.pdf) [...] is **available** as `5e781983-a6c9-4ea3-bcdd-b33ed6998381.pdf` in **this repository**.

**Comment by formlessdao** [comment]
I can't find it.

**Comment by user202729** [comment]
I said "this repository". https://github.com/user202729/plover-resources/blob/main/5e781983-a6c9-4ea3-bcdd-b33ed6998381.pdf
