### ISSUE TITLE
Stenovations Dictionaries Contain Errors

### ISSUE THREAD

**Issue by tremm008** [user202729/plover-resources#2]
Hi,
I know for sure that the REALWRITE/realtime (hereby referred to as RW/RT) dictionary from Stenovations ("realwrite.json") contains errors. It's not an official dictionary. It's a great learning resource, but appears to be a personal dictionary from someone who learned RW/RT and made their own tweaks. There are entries that run counter to the official theory books and break core rules of the theory. realwrite.json needs a disclaimer so as to clear up any confusion among learners. 

Good examples of discrepancies:

- `TPAL` is defined as "fall." The theory book has an entire section explaining why the theory uses `AU` for these sounds. `TPAUL` doesn't appear in realwrite.json as "fall," however. It only appears as a suffix for `{^iful}`. The theory textbooks themselves have some conflicts about this, but I know there's multiple editions. In mine, "fall" is definitely `TPAUL`, however.
- `HRAPS` defined as "laps." RW/RT's resolves conflicts between plurals and words that end with the letter S or the letters SE by using the final Z for plurals. "Laps" should be `HRAPZ`. `HRAPS` would be "lapse."

These dictionaries are, again, very useful for learners, but I think it's confusing to offer these dictionaries without a disclaimer, as many learners will try to reverse-engineer a theory from the dictionary. Using realtime.json to reverse-engineer RW/RT theory would result in something very different from the actual published theory.

**Comment by user202729** [comment]
I think "downloaded from Stenovations" is enough of a disclaimer, but will add.

**Comment by tremm008** [comment]
A few people on Discord have reacted with surprise when I tell them the
dictionary has errors.
